repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: openfaas
    url: https://openfaas.github.io/faas-netes
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
releases:
  - name: namespaces
    chart: incubator/raw
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: openfaas
              labels:
                role: openfaas-system
                access: openfaas-system
            spec: {}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: openfaas-fn
              labels:
                role: openfaas-fn
            spec: {}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: nginx
            spec: {}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: keycloak
            spec: {}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: envoy
            spec: {}
          - apiVersion: v1
            kind: Secret
            type: Opaque
            metadata:
              name: keycloak-admin-passwd
              namespace: keycloak
            data:
              password: {{ requiredEnv "KEYCLOAK_PASSWORD" | trim | b64enc }}
  - name: nginx-ingress
    namespace: nginx
    chart: stable/nginx-ingress
    needs:
      - namespaces
    set:
      - name: controller.kind
        value: DaemonSet
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 30443
  - name: openfaas
    namespace: openfaas
    chart: openfaas/openfaas
    needs:
      - namespaces
    set:
      - name: basic_auth
        value: false
      - name: functionNamespace
        value: openfaas-fn
      - name: exposeServices
        value: false
      - name: serviceType
        value: ClusterIP
      - name: operator.create
        value: true
      - name: operator.createCRD
        value: true
      - name: faasnetes.imagePullPolicy
        value: Never
      - name: ingress.enabled
        value: false
  - name: keycloak
    namespace: keycloak
    chart: codecentric/keycloak
    set:
      - name: keycloak.ingress.enabled
        value: true
      - name: keycloak.ingress.hosts
        values:
          - keycloak.openfaas.local
      - name: keycloak.username
        value: admin
      - name: keycloak.existingSecret
        value: keycloak-admin-passwd
  - name: envoy
    namespace: envoy
    chart: ./envoy
    needs:
      - namespaces
    values:
      - "./envoy/values.yaml"
    set:
      - name: envoy.keycloakHostIp
        value: "{{ requiredEnv "KEYCLOAK_IP" | trim }}"
    wait: true
