apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy.fullname" . }}-config
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (.Files.Get "files/envoy-config.yaml") . | nindent 4 }}
