apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.envoy.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "envoy.selectorLabels" . | nindent 4 }}
